name: Build & Push
on:
  schedule:
    # We want to build a new image right after trivy publishes new DBs but we can't subscribe to those events so instead we use cron
    # The trivy-db repo builds at the 0th minute every 6 hours so we start at the 30th minute to give the builds some time to execute
    # https://github.com/aquasecurity/trivy-db/blob/db9bf07792afba73dceb20b99723c8af007da1f8/.github/workflows/cron.yml#L5
    # https://github.com/aquasecurity/trivy-java-db/blob/be4b443fed1db725fb1d21688567a5b644df9ea7/.github/workflows/cron.yml#L5
    - cron: '30 */6 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: bored-engineer
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          # These are the same platforms supported upstream by aquasecurity/trivy images
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ghcr.io/bored-engineer/trivy-offline:latest
